@startuml Fase

[*]         --> Suspenção
Suspenção   --> Busca

state Busca {
    [*]     --> entrada : [em inicialização]
    [*]     --> ação : [não em inicialização]
    ação    --> [*]
    entrada --> [*]

    entrada : preparar microoperações de busca
    entrada : em inicialização é falso
    ação    : executar microoperação da fila
}

Busca --> Busca         : [fila não vazia]
Busca --> Decodificação : [fila vazia]

@enduml