@startuml FluxoSimples

[*]             --> Suspensão
Suspensão       --> Busca
Busca           --> Decodificação
Decodificação   --> Endereçamento
Endereçamento   --> Execução
Execução        --> Suspensão

@enduml