@startuml ÚnicaMicrooperação

state "Próxima fase" as ProxFase

[*] --> Fase

Fase --> Suspensão  : [unica microperação] / suspensão retornará para essa fase
Fase --> ProxFase   : [fila vazia]
Fase --> Fase       : [fila não vazia]

@enduml